// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL5t_IhSisGVI4eG-kRg3wPAvC5V-SG6g',
    appId: '1:758683111450:web:37e21ac7878e0629fe81a3',
    messagingSenderId: '758683111450',
    projectId: 'flutter-food-app-71f5d',
    authDomain: 'flutter-food-app-71f5d.firebaseapp.com',
    databaseURL: 'https://flutter-food-app-71f5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-food-app-71f5d.appspot.com',
    measurementId: 'G-HRJ0TT7CE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn1k7oPPo5FijMm9ZNYw1I5P4RVqrlxHk',
    appId: '1:758683111450:android:603032636e38e9d8fe81a3',
    messagingSenderId: '758683111450',
    projectId: 'flutter-food-app-71f5d',
    databaseURL: 'https://flutter-food-app-71f5d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-food-app-71f5d.appspot.com',
  );
}
